"""add new column

Revision ID: 889d808cf345
Revises: 535a99eb8e12
Create Date: 2019-07-31 07:49:36.402397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889d808cf345'
down_revision = '535a99eb8e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
