"""Create bio and profile pic columns

Revision ID: a7f78806dd2d
Revises: 0a6649279255
Create Date: 2019-07-31 13:52:05.685227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f78806dd2d'
down_revision = '0a6649279255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_patch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_patch')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
